### ISSUE TITLE
Transitive dependencies

### ISSUE THREAD

**Issue by vrozov** [siom79/japicmp#83]
Is there a way to disable new behavior of 0.6? It does not behave correctly and tries to pull dependency that does not exist.

```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.0:cmp (default) on project apex-api: Could not resolve org.apache.zookeeper:zookeeper:jar:3.4.5:compile: Could not transfer artifact com.sun.jmx:jmxri:jar:1.2.1 from/to java.net (https://maven-repository.dev.java.net/nonav/repository): Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available connector factories: BasicRepositoryConnectorFactory
[ERROR] com.sun.jmx:jmxri:jar:1.2.1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR] ossrh (https://oss.sonatype.org/content/repositories/snapshots, releases=true, snapshots=true),
[ERROR] datatorrent (https://www.datatorrent.com/maven/content/repositories/releases/, releases=true, snapshots=false),
[ERROR] apache.snapshots (http://repository.apache.org/snapshots, releases=false, snapshots=true),
[ERROR] central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false),
[ERROR] java.net (https://maven-repository.dev.java.net/nonav/repository, releases=true, snapshots=true)
[ERROR] Path to dependency:
[ERROR] 1) org.apache.zookeeper:zookeeper:jar:3.4.5
[ERROR] 2) log4j:log4j:jar:1.2.15
[ERROR] 3) com.sun.jmx:jmxri:jar:1.2.1: Cannot access https://maven-repository.dev.java.net/nonav/repository with type legacy using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout legacy
[ERROR] -> [Help 1]
```

**Comment by siom79** [comment]
According to the pom of Log4j (see [here](https://repo1.maven.org/maven2/log4j/log4j/1.2.15/log4j-1.2.15.pom) the missing dependency jmxri is really missing in the central maven repository. 

A solution proposed [here](http://stackoverflow.com/questions/4908651/the-following-artifacts-could-not-be-resolved-javax-jmsjmsjar1-1) is to exclude the missing dependency from the zookeeper dependency. Have you already tried this?

**Comment by vrozov** [comment]
The project does not directly depend on zookeeper. It depends on hadoop-common:2.2.0 and hadoop-common.pom properly excludes jmxri dependency.

The problem seems to be with the new 0.6 dependency handling, not with how dependencies are defined in our project. It properly compiles with the prior version of japicmp.

**Comment by siom79** [comment]
Where do you specify the dependency on hadoop-common:2.2.0? In the enclosing pom where japicmp is declared or did you add it as an `dependency` to the `configuration` section of japicmp?

What has been changed is that in version 0.6.0 project dependencies are resolved transitively. My tests have shown that this makes no big difference to the normal retrieval of project dependencies. But maybe there is a slight difference regarding excluded dependencies.

**Comment by vrozov** [comment]
It is defined in the enclosing pom as project dependency, not as japicmp dependency.

**Comment by siom79** [comment]
With your help I was able to reproduce the issue. The problem is that I have introduced a transitive resolution of all project artifacts. Unfortunately this also resolves excluded dependencies from the hadoop-common:2.2.0 pom.

On the `develop` branch I have disabled this transitive resolution and my reconstructed test case with the hadoop-commons pom works now.

If you like you can test that yourself:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
mvn install
```
Let me know what you think.

**Comment by vrozov** [comment]
I tried it and I still see the error. I can send you build.log over e-mail.

**Comment by siom79** [comment]
Released with version 0.6.1.
