### ISSUE TITLE
Include classes/methods based on annotations

### ISSUE THREAD

**Issue by rmetzger** [siom79/japicmp#88]
I'm planning to use this plugin, but we are planning to give our users API stability guarantees only for certain, "public APIs".
To make an API public, we use java annotations. Therefore, it would be great if japicmp would allow to define class-inclusions based on annotations.

Are there plans to add support for this?
Are there any fundamental reasons not to support this?

**Comment by rmetzger** [comment]
I'm currently implementing the feature myself :)

**Comment by siom79** [comment]
Thank you for your work. I have just merged it on the `develop` branch.

Currently I am reviewing it. What I would like to change is that you can exclude single fields or methods with an annotation:
```
public class ClassWithMembersToExclude {
	@Exclude
	public String CONSTANT = "C";

	@Exclude
	public void methodToExclude() {

	}
}
```
At the moment this does not work, because the `Filter` interface has three methods and all of them are applied in order to evaluate expressions like `package.Class#fieldToInclude`. In this javadoc-like expression it has to be tested if the field belongs to the class `package.Class` and has the name `fieldToInclude`.
In order for that to work, the implementation of `Filters` has to be changed.

**Comment by rmetzger** [comment]
Cool, thank you!
I totally agree changing the filter implementation to make exclusions work.

**Comment by rmetzger** [comment]
I will test the exclusion with our code.

When do you plan to release a new version with the new feature?

**Comment by siom79** [comment]
I have planned the next release for December. Hopefully I will find next week some time to modify the Filters class as mentioned above.

**Comment by rmetzger** [comment]
One quick follow up question on this: Right now it seems that `public static` inner classes are not included even if the parent class is a public interface.
I'm wondering whether this is intended and what the best default behavior would be.

**Comment by siom79** [comment]
Inner classes that are declared `public static` are treated as normal classes. Take for example the class [japicmp.test.Superclasses$SuperClassChanges](https://github.com/siom79/japicmp/blob/master/japicmp-testbase/japicmp-test-v1/src/main/java/japicmp/test/Superclasses.java#L29). This is reported in the diff as:
```
***! MODIFIED CLASS: PUBLIC STATIC japicmp.test.Superclasses$SuperClassChanges  (not serializable)
	***! MODIFIED SUPERCLASS: japicmp.test.Superclasses$SuperclassB (<- japicmp.test.Superclasses$SuperclassA)
```
Do you have an example that shows different behavior?

**Comment by rmetzger** [comment]
This feature has been marked as "done", However, I'm not sure if its properly working. I created a Flink 1.0-SNAPSHOT release (into my local maven repository), then I updated the pom version to 1.1-SNAPSHOT, set the old version to 1.0-SNAPSHOT in japicmp and changed some interfaces, but it didn't detect any changes.
Only after changing the include definition, it was working:

Works:
```xml
<includes>
	<include>org.apache.flink</include>
</includes>
```

Doesn't work:
```xml
<includes>
	<include>@org.apache.flink.annotation.PublicInterface</include>
</includes>
```
I've tested with commit: 023bc209a8c42f150e16c0367c4afabcc345224c

Here are some sample reports with annotation filters (not detecting anything)
[JApiCmp-Report-withAnnotationFilters.pdf](https://github.com/siom79/japicmp/files/62470/JApiCmp-Report-withAnnotationFilters.pdf)

With the working filter, detecting changes:
[JApiCmp-Report-withPackageIncludeFilter.pdf](https://github.com/siom79/japicmp/files/62473/JApiCmp-Report-withPackageIncludeFilter.pdf)

Not sure what I'm doing wrong.

**Comment by siom79** [comment]
How does `org.apache.flink.core.io.LocatableInputSplit` look like, i.e. where is the annotation?

**Comment by rmetzger** [comment]
The annotation is on the type.
```java
@PublicInterface
public class LocatableInputSplit implements InputSplit, java.io.Serializable {
```

**Comment by siom79** [comment]
The point that you are facing is that inner classes (`org.apache.flink.core.io.LocatableInputSplit$NewInnerClass`) are compiled to separate class files. When japicmp scans the archive, it stumbles upon the class file `org.apache.flink.core.io.LocatableInputSplit$NewInnerClass.class` and in your first case it notices that it belongs to the package `org.apache.flink`, hence it is included. In your second case it scans for the annotation `@org.apache.flink.annotation.PublicInterface`, which is not on your inner class, and does not include the class.

But fortunately javassist has a method that allows to retrieve the declaring class for an inner class. Hence I have just committed a change set to the `develop` branch that also considers inner classes.

**Comment by rmetzger** [comment]
Okay, I see the point with the inner class. Thanks a lot for fixing it!

But why does the `JApiCmp-Report-withAnnotationFilters.pdf` report not contain any changes at all? As you can see from the second report, I added a new method `public String hallo();` to the class.

**Comment by siom79** [comment]
Is this still reproducible? I have added a test case that shows that new methods of annotated classes are detected.

**Comment by rmetzger** [comment]
Yes, I think the issue is still reproducible.

Also, the plugin does not warn or fail if I specify an exclusion/inclusion annotation with a nonexistent type:
```xml
<includes>
	<include>@org.apache.flink.annotation.Public</include>
	<include>@com.acme.doesnt.exist.Class</include>
</includes>
```
afaik even with the recent changes, we should be able to detect when a class is not present at all?

To reproduce the issue, here are the relevant parts of the class:
```java

@Public
public class LocatableInputSplit implements InputSplit, java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private static final String[] EMPTY_ARR = new String[0];
	
	/** The number of the split. */
	private final int splitNumber;

	/** The names of the hosts storing the data this input split refers to. */
	private final String[] hostnames;

	// --------------------------------------------------------------------------------------------


	public String hallo() {
		return "Hallo";
	}
	public int someOther() {
		return 33;
	}

	public static class MyNewClass {
		public int b;
		public long a;
	}
```

this is the report: 
![image](https://cloud.githubusercontent.com/assets/89049/11836272/db09f5b6-a3d9-11e5-8265-be96a42f6ff4.png)
As you can see, the new methods I've added are missing

This is my plugin configuration
```xml
<plugin>
				<groupId>com.github.siom79.japicmp</groupId>
				<artifactId>japicmp-maven-plugin</artifactId>
				<version>0.6.2-SNAPSHOT</version>
				<configuration>
					<oldVersion>
						<dependency>
							<groupId>org.apache.flink</groupId>
							<artifactId>${project.artifactId}</artifactId>
							<version>1.0-SNAPSHOT</version>
							<type>${project.packaging}</type>
						</dependency>
					</oldVersion>
					<newVersion>
						<file>
							<path>${project.build.directory}/${project.artifactId}-${project.version}.${project.packaging}</path>
						</file>
					</newVersion>
					<parameter>
						<onlyModified>true</onlyModified>
						<includes>
							<include>@org.apache.flink.annotation.Public</include>
							<include>@com.acme.doesnt.exist.Class</include>
						</includes>
						<excludes>
							<exclude>@org.apache.flink.annotation.Experimental</exclude>
						</excludes>
						<accessModifier>public</accessModifier>
						<breakBuildOnModifications>false</breakBuildOnModifications>
						<breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
						<onlyBinaryIncompatible>false</onlyBinaryIncompatible>
						<includeSynthetic>true</includeSynthetic>
						<ignoreMissingClasses>false</ignoreMissingClasses>
						<skipPomModules>true</skipPomModules>
					</parameter>
					<skip>false</skip>
					<dependencies>
						<dependency>
							<groupId>org.apache.flink</groupId>
							<artifactId>flink-annotations</artifactId>
							<version>1.0-SNAPSHOT</version>
						</dependency>
					</dependencies>
				</configuration>
				<executions>
					<execution>
						<phase>verify</phase>
						<goals>
							<goal>cmp</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

and here are the two jar files (I renamed them to zip so that GH accepts them):
[flink-core-1.1-SNAPSHOT.zip](https://github.com/siom79/japicmp/files/63755/flink-core-1.1-SNAPSHOT.zip)

[flink-core-1.0-SNAPSHOT.zip](https://github.com/siom79/japicmp/files/63757/flink-core-1.0-SNAPSHOT.zip)


With the following includes, it also doesn't work:
```
<includes>
	<include>org.apache.flink</include>
	<include>@com.acme.doesnt.exist.Class</include>
</includes>
```

with those it finally works:
```
<includes>
		<include>org.apache.flink</include>
		<!--<include>@com.acme.doesnt.exist.Class</include> -->
</includes>
```
So it seems that the presence of one annotation-based filter is messing up the report.

prove:
![image](https://cloud.githubusercontent.com/assets/89049/11836430/f7e90b08-a3da-11e5-979c-40bc05a2e26f.png)

**Comment by siom79** [comment]
The point here is that you don't have the annotation on each element of the class. You only want to set it on the class and then all methods and fields and inner classes are included. Currently it is only evaluated on the class level and all methods that are not annotated are not included. I think  it should be possible to change that as you should be able to exclude elements of the included class with another exclude annotation (to be tested).

As the current implementation does not load the annotation from the classpath, you can specify annotations that do not exist...

**Comment by siom79** [comment]
I have committed a change set that allows you to track changes on classes that are annotated with an include annotation.

Let me know what you think.

**Comment by chandnisingh** [comment]
If I have annotated a package with `@Unstable` and that annotation is in the excluded list, will this change exclude all the classes under that package?

Thanks!

**Comment by rmetzger** [comment]
@siom79: Awesome, I've checked the latest develop branch and its working!
Thank you also for fixing the `toString()` method of the annotation filter.

**Comment by siom79** [comment]
@chandnisingh: Just committed a change set that also considers annotations on packages.

**Comment by siom79** [comment]
Released with 0.6.2.

**Comment by chandnisingh** [comment]
@siom79 @rmetzger thanks for this change

**Comment by chandnisingh** [comment]
@siom79 I tried annotation for exclusion and it doesn't seem to be working. Did this change included excluded annotation as well?

**Comment by siom79** [comment]
@chandnisingh At least there are [test cases](https://github.com/siom79/japicmp/blob/master/japicmp-testbase/japicmp-test/src/test/java/japicmp/test/AnnotationFilterTest.java) for excluding class elements or packages.

How exactly do you want to exclude?

**Comment by chandnisingh** [comment]
@siom79 
This is how the plugin configuration looks like
```
 <parameter>
              <onlyModified>true</onlyModified>
              <accessModifier>protected</accessModifier>
              <breakBuildOnModifications>false</breakBuildOnModifications>
              <breakBuildOnBinaryIncompatibleModifications>true</breakBuildOnBinaryIncompatibleModifications>
              <onlyBinaryIncompatible>false</onlyBinaryIncompatible>
              <includeSynthetic>false</includeSynthetic>
              <ignoreMissingClasses>true</ignoreMissingClasses>
              <excludes>
                <exclude>@org.apache.hadoop.classification.InterfaceStability.Evolving</exclude>
                <exclude>@org.apache.hadoop.classification.InterfaceStability.Unstable</exclude>
              </excludes>
            </parameter>
```
We have marked classes as 
```
@org.apache.hadoop.classification.InterfaceStability.Evolving
public abstract class AbstractFTPInputOperator<T> extends AbstractFileInputOperator<T>
```

However when I make a backward incompatible change in that class, the plugin complains
```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2:cmp (default) on project malhar-library: Breaking the build because there is at least one modified class: com.datatorrent.lib.io.AbstractFTPInputOperator ->
```

**Comment by siom79** [comment]
Is it possible that `@org.apache.hadoop.classification.InterfaceStability.Evolving` is an inner annotation of the class `org.apache.hadoop.classification.InterfaceStability`? In this case you would have to write `@org.apache.hadoop.classification.InterfaceStability$Evolving`. Let me know if this works.

**Comment by chandnisingh** [comment]
Yes org.apache.hadoop.classification.InterfaceStability.Evolving is an inner annotation of the class org.apache.hadoop.classification.InterfaceStability. 
When I write  `@org.apache.hadoop.classification.InterfaceStability$Evolving`, I see that at least the classes are being excluded but now the plugin complains that the class (marked with @org.apache.hadoop.classification.InterfaceStability.Evolving) is removed.

```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2:cmp (default) on project malhar-library: Breaking the build because there is at least one modified class: com.datatorrent.lib.io.AbstractFTPInputOperator -> [Help 1]
```

This is the report
```
REMOVED (!)	com.datatorrent.lib.io.AbstractFTPInputOperator
```
Can you please advise?

**Comment by siom79** [comment]
Is the class `com.datatorrent.lib.io.AbstractFTPInputOperator` also annotated in the old version?

**Comment by chandnisingh** [comment]
No it isn't

**Comment by siom79** [comment]
Ok, then it is included in den old version and excluded in the new version and hence detected as "removed".

**Comment by chandnisingh** [comment]
Shouldn't it be ignored and not detected as removed?
When we add `<exclude>com.datatorrent.lib.io.AbstractFTPInputOperator</exclude>` 
then the plugin doesn't complain. With annotation we basically try to achieve the same thing by annotating the class

**Comment by siom79** [comment]
When you exclude the class then it is removed from the old and the new version because it exists in both. Would you have annotated it also in the old version everything would be ok. Why can a class become evolving or unstable when it wasn'the in the old version?

On the other hand when you remove the annotation unstable in the new version of a class then it would appear as "new" class. 

Beyond that the exclude option is used to make classes or class members invisible. An unstable or evolving class is semantically maybe something different. It is visible but users should be aware that it will change over time. So why exclude it? Your problem is more that you don't want to break the build if unstable or evolving classes change. Maybe we need a new option here...

**Comment by chandnisingh** [comment]
We adopted this practice of annotating classes as Evolving/Unstable quite later. We have around hundreds of classes and when we added semantic version plugin, every thing got included. With new classes we started modifying the plugin configuration with exclusions. This is when we realized we needed this change and mark selected classes Evolving/Unstable. 

However I think in the next version we will just identify and mark these classes as Evolving and Unstable and the version after that we will add the exclusion annotation.
